version: "3.0"

services:

  api:
    build:
      context: .
    image: leetcode-mvp-services
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  problems:
    build:
      context: .
    image: leetcode-mvp-services
    env_file: docker-compose.env
    environment:
      SERVICES: problems
    links:
      - nats
      - mongodb
    depends_on:
      - nats
      - mongodb

  answers:
    build:
      context: .
    image: leetcode-mvp-services
    env_file: docker-compose.env
    environment:
      SERVICES: answers
    links:
      - nats
      - mongodb
    depends_on:
      - nats
      - mongodb


  nats:
    image: nats

  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - mongodb:/bitnami
  
  runner:
    image: postor/leetcode-mvp-runner
    env_file: docker-compose.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/leetcode-mvp-runner:/tmp/leetcode-mvp-runner

  web:
    image: postor/leetcode-mvp-web
    env_file: docker-compose.env
    ports:
      - "80:3000"      
    links:
      - api
      - runner
    depends_on:
      - api
      - runner
  
volumes:
  mongodb: