version: "3.0"

services:

  api:
    build:
      context: .
    image: leetcode-mvp-services
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 3000
    restart: always
    links:
      - nats
    depends_on:
      - nats
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=api"
      - "traefik.port=3000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  problems:
    build:
      context: .
    image: leetcode-mvp-services
    env_file: docker-compose.env
    environment:
      SERVICES: problems
    restart: always
    links:
      - nats
      - mongodb
    depends_on:
      - nats
      - mongodb

  answers:
    build:
      context: .
    image: leetcode-mvp-services
    env_file: docker-compose.env
    environment:
      SERVICES: answers
    restart: always
    links:
      - nats
      - mongodb
    depends_on:
      - nats
      - mongodb

  nats:
    image: nats
    restart: always

  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - mongodb:/bitnami
    restart: always
  
  runner:
    image: postor/leetcode-mvp-runner
    env_file: docker-compose.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/leetcode-mvp-runner:/tmp/leetcode-mvp-runner
    restart: always

  web:
    image: postor/leetcode-mvp-web
    env_file: docker-compose.env
    ports:
      - "80:3000"   
    restart: always   
    links:
      - api
      - runner
    depends_on:
      - api
      - runner
  
volumes:
  mongodb: